name: ci
on: push
jobs:
  ci-linux:
    name: linux ci
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install dependencies
        run: sudo apt install meson
      - name: run tests
        env:
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CXX: clang++
        run: ./test.sh
  ci-windows:
    name: windows ci
    runs-on: windows-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install dependencies
        run: |
            choco install meson
            choco install ninja
      - name: run tests
        shell: bash
        env:
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./test.sh
